### ISSUE TITLE
Better HTTP error handling

### ISSUE THREAD

**Issue by Civil** [lomik/graphite-clickhouse#1]
I've got the following concerns about current http error handling:
1. There is no way on the client to find out what's this error about. 
2. In case of unsupported parameter you should return an error (e.x. for format)

**Comment by bzed** [comment]
Also: if the request to clickhouse returns 503 or other errors, there should be an error raised and forwarded to the client.

At the moment the result of a 503 from clickhouse (or its haproxy) in combination with graphite-clickhouse and carbonapi is an empty set without error at all. This is far away from optimal.

**Comment by Felixoid** [comment]
hello gentlemen.

I believe the state of the project is much better now?
