### ISSUE TITLE
receive two different metrics at the same time with almost the same query

### ISSUE THREAD

**Issue by Vlggg** [lomik/graphite-clickhouse#107]
Hello,
We use carbonapi-0.14.1 + carbon-clickhouse-0.11.1-1 + graphite-clickhouse-0.11.7 for gather metrics and monitor it with queries. For some reason, we see really strange things. Sometimes I see a new time point in the answer has value None. If I execute the same query at the same time but change the time period, I will see the time point has value.
Examples:
URL with query  
`http://graphite:9080/render?target=groupByTags(seriesByTag('name=k8s.kubernetes_deployment.replicas_available', 'datacenter=dc1', 'deployment_name=webui'), 'last', '')&from=-5min&until=-4min&format=json`  
response  
`[{u'tags': {u'datacenter': u'dc1', u'host': u'host1', u'namespace': u'prod', u'name': u'k8s.kubernetes_deployment.replicas_available', u'deployment_name': u'webui'}, u'target': u'k8s.kuberne
tes_deployment.replicas_available;=', u'datapoints': [[2, 1602365950], [2, 1602365960], [2, 1602365970], [2, 1602365980], [2, 1602365990], [2, 1602366000], [None, 1602366010]]}]`  
URL with almost the same query  
`http://graphite:9080/render?target=groupByTags(seriesByTag('name=k8s.kubernetes_deployment.replicas_available', 'datacenter=dc1', 'deployment_name=webui'), 'last', '')&from=-5min&until=-1min&format=json`  
response  
`[{u'tags': {u'datacenter': u'dc1', u'host': u'host1', u'namespace': u'prod', u'name': u'k8s.kubernetes_deployment.replicas_available', u'deployment_name': u'webui'}, u'target': u'k8s.kuberne
tes_deployment.replicas_available;=', u'datapoints': [[2, 1602365960], [2, 1602365970], [2, 1602365980], [2, 1602365990], [2, 1602366000], [2, 1602366010], [2, 1602366020], [2, 1602366030], [2, 1602366040], [2, 1602366050], [2, 1602366060
], [2, 1602366070], [2, 1602366080], [2, 1602366090], [2, 1602366100], [2, 1602366110], [2, 1602366120], [2, 1602366130], [2, 1602366140], [2, 1602366150], [2, 1602366160], [2, 1602366170], [2, 1602366180], [2, 1602366190]]}]`

As you can see in the first query at 1602366010 value None but at the same time in the almost same query, I see value in place and equal 2.
difference in queries:
from=-5min&until=-4min
As per https://github.com/go-graphite/carbonapi/issues/528 I performed tests and we found this is not a bug of carbonapi.
Configuration of graphite-clickhouse:
```
[common]
listen = ":9090"
max-cpu = 2

[clickhouse]
url = "https://user:password@clickhouse:8124"
tagged-table = "graphite.graphite_tagged"
data-table = "graphite.graphite"
index-table = "graphite.graphite_index"
tree-table = "graphite.graphite_tree"
date-tree-table = ""
#date-tree-table-version = 1
index-use-daily = true
index-timeout = "15s"
rollup-conf = "/etc/graphite-clickhouse/rollup.xml"
extra-prefix = ""
data-timeout = "1m0s"
tree-timeout = "1m0s"

[carbonlink]
server = ""
threads-per-request = 10
connect-timeout = "50ms"
query-timeout = "50ms"
total-timeout = "500ms"

[[logging]]
logger = ""
file = "/var/log/graphite-clickhouse/graphite-clickhouse.log"
level = "info"
encoding = "mixed"
encoding-time = "iso8601"
encoding-duration = "seconds"
```
**Question**
Do you have any idea what I should test to understand why it's happening?

**Comment by Felixoid** [comment]
Hey.

First, I guess it makes sense to take a query from the log and apply it. It should be starting with `SELECT Path, Time, Value, Timestamp` for version 0.11.7

Btw, it as well makes sense to try the latest version, to see if it still exists

**Comment by Felixoid** [comment]
Could be fixed in https://github.com/lomik/graphite-clickhouse/pull/84

**Comment by Vlggg** [comment]
@Felixoid, thank you for your answer!

I tested for periods from=-59min&until=-58min and from=-60min&until=-55min and saw the same result.
I will test the new version and back with the results. Looks like https://github.com/lomik/graphite-clickhouse/pull/84 really can help us.

**Comment by Vlggg** [comment]
I tried the latest stable version(v0.12.0) and saw the same behavior. I found how to reproduce this.
query
```
http://graphite:9080/render?target=groupByTags(seriesByTag('name=k8s.kubernetes_deployment.replicas_available', 'datacenter=dc1', 'deployment_name=webui'), 'last', '')&from=1603994560&until=1603994610&noCache&format=json
```
respone
```
[{u'tags': {u'datacenter': u'dc1', u'host': u'host1', u'namespace': u'prod', u'name': u'k8s.kubernetes_deployment.replicas_available', u'deployment_name': u'webui'}, u'target': u'k8s.kuberne tes_deployment.replicas_available;=', u'datapoints': [[2, 1603994560], [2, 1603994570], [2, 1603994580], [2, 1603994590], [2, 1603994600], [None, 1603994610]]}]
[2, 2, 2, 2, 2, None]
```
In logs of graphite-clickhouse I found this SELECT and it looks a bit different and returns 5 datapoints.
query to clickhouse(last part in query with "format" has been removed by me)
```
SELECT Path, groupArray(Time), groupArray(Value), groupArray(Timestamp) FROM graphite.graphite PREWHERE Date >='2020-10-29' AND Date <= '2020-10-29' WHERE (Path IN ('k8s.kubernetes_deployment.replicas_available?datacenter=dc1&deployment_name=webui&host=host1&namespace=prod','k8s.kubernetes_deployment.replicas_available?datacenter=dc1&deployment<...>com&namespace=prod')) AND (Time >= 1603994560 AND Time <= 1603994609) GROUP BY Path
```
response
```
┌─Path────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─groupArray(Time)─────────────────────────────────────────┬─groupArray(Value)─┬─groupArray(Timestamp)────────────────────────────────────┐
│ k8s.kubernetes_deployment.replicas_available?datacenter=dc1&deployment_name=webui&host=host1&namespace=prod │ [1603994560,1603994570,1603994580,1603994590,1603994600] │ [2,2,2,2,2]       │ [1603994580,1603994580,1603994610,1603994610,1603994610] │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────────────┴───────────────────┴──────────────────────────────────────────────────────────┘

```

**Comment by Felixoid** [comment]
I see. It was broken in another way before #84, but I've broken it in f3583294580b6a83b66b95330ece3093fe3acf7a ([was](https://github.com/lomik/graphite-clickhouse/commit/f3583294580b6a83b66b95330ece3093fe3acf7a#diff-3b33b488ddb3d2f64559863b911a646de7e4ead1967262b15699b5eb94c32f22L226), [become](https://github.com/lomik/graphite-clickhouse/commit/f3583294580b6a83b66b95330ece3093fe3acf7a#diff-dd0047c86eb3449b47b84a87cbc1cf2bbbb726459e13916af2a1586abcea4399R182))

Before it always inclusive, and now it is exclusive rounding. It makes sense to fix it, for sure.

**Comment by Felixoid** [comment]
@Vlggg please, try out the linked PR

**Comment by Felixoid** [comment]
Hey @Vlggg, any following here?

**Comment by Vlggg** [comment]
Hello @Felixoid, I will test it today. Sorry for the long silence, I didn't have a laptop and internet connection for the last few days.

**Comment by Vlggg** [comment]
Hello @Felixoid,
I tested PR and it works very well. In the test, I asked for 1 minute and received sometimes 7 datapoints as before but the last datapoint has value(before PR, I received `None` in 7th datapoint). Also, I tested the query from https://github.com/lomik/graphite-clickhouse/issues/107#issuecomment-719546091 and received a correct response. Thank you a lot!
```
http://graphite:9080/render?target=groupByTags(seriesByTag('name=k8s.kubernetes_deployment.replicas_available', 'datacenter=dc1', 'deployment_name=webui'), 'last', '')&from=-59min&until=-58min&noCache&forma
t=json
[{u'tags': {u'datacenter': u'dc1', u'host': u'host1', u'namespace': u'prod', u'name': u'k8s.kubernetes_deployment.replicas_available', u'deployment_name': u'webui'}, u'target': u'k8s.kuberne
tes_deployment.replicas_available;=', u'datapoints': [[2, 1604493510], [2, 1604493520], [2, 1604493530], [2, 1604493540], [2, 1604493550], [2, 1604493560], [2, 1604493570]]}]
```
