### ISSUE TITLE
clickhouse query log truncation

### ISSUE THREAD

**Issue by spoofedpacket** [lomik/graphite-clickhouse#114]
For large queries, I often see the query logs getting truncated with a "<...>" in the string. Is there a way to configure logging to display the entire query that was executed in clickhouse?

**Comment by Felixoid** [comment]
Hello. No, and yes :-j

No: there's no way to configure this particular log. This is hardcoded in https://github.com/lomik/graphite-clickhouse/blob/master/helper/clickhouse/clickhouse.go#L164

Yes: if you want to see every metric that is queried, you would like to try the latest master code. In #100 the changes to a query were added, which builds the external data table. And a way to dump the external data for debugging is now. See https://github.com/lomik/graphite-clickhouse/pull/100/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R180-R186

**Comment by Felixoid** [comment]
Closing since the debug for http request is sufficient
