### ISSUE TITLE
Get peer ip from header x-forwarded-for 

### ISSUE THREAD

**Issue by ihard** [lomik/graphite-clickhouse#117]
Is it possible to output some custom headers of the x-forwarded-for type to the log? 
It would be convenient in the analysis of problems. 
Now in the log only peer with the address 127.0.0.1 as the proxy is located on top. 
The x-forwarded-for and x-real-ip headers are received but apparently not processed in any way.

**Comment by Felixoid** [comment]
Hey @ihard 
https://github.com/lomik/graphite-clickhouse/suites/2064144129/artifacts/41687966
Can you see if the artifact from the linked PR does what is desired?

It's built in https://github.com/lomik/graphite-clickhouse/pull/129/checks?check_run_id=1922965409

**Comment by ihard** [comment]
Everything works as expected. The log shows the ip of the users. Thanks!
