### ISSUE TITLE
new Clickhouse aggregation yields "random" data for aggregation method "any"

### ISSUE THREAD

**Issue by chbuescher** [lomik/graphite-clickhouse#120]
The "old" any-aggregation always yield the first non-null value, but because the data is not ordered when doing the aggregation in clickhouse, really any value of the given interval may be returned. When calculating differences of the values this results in unwanted spikes.
To fix this behaviour I use a subselect to order the data before aggregating it. (render/query.go)
This restores the original behaviour.

const queryAggregated = `SELECT Path,
	arrayFilter(x->isNotNull(x), anyOrNullResample(%[1]d, %[2]d, %[3]d)(toUInt32(intDiv(Time, %[3]d)*%[3]d), Time)),
	arrayFilter(x->isNotNull(x), %[4]sOrNullResample(%[1]d, %[2]d, %[3]d)(Value, Time))
FROM (SELECT Path, Time, Value FROM %[5]s 
%[6]s
%[7]s
ORDER BY Time) 
GROUP BY Path
FORMAT RowBinary`

**Comment by Felixoid** [comment]
Hello. Thank you for your feedback

The `any` function is non-determined, [ref](https://clickhouse.tech/docs/en/sql-reference/aggregate-functions/reference/any/). It's the closest possible option for the whisper's `first` aggregation, but not the perfect one.

Generally, subselect is a bad idea for shared data. The initiator CH node will receive the whole data from the subquery before aggregation, so the SQL-side aggregation loses any sense. See https://github.com/ClickHouse/graphouse/pull/130.

Sorry, besides disabling the internal-aggregation, I can only suggest trying [max_threads](https://clickhouse.tech/docs/en/operations/settings/settings/#settings-max_parallel_replicas) setting. But it will slow down the query, for sure.
