### ISSUE TITLE
Get available tag values from tagged table

### ISSUE THREAD

**Issue by Perlovka** [lomik/graphite-clickhouse#16]
Hi,

In prometheus grafana data source one could get available tag values with the following function:

`
label_values(metric_name{label1=~"name.*",label2=~"value.*"},hostname)
`

This will return all **hostname** label values where **label1** and **label2** values matches regex expression

http://docs.grafana.org/features/datasources/prometheus/#query-variable

Is it possible to achieve same functionality with graphite datasource and graphite-clickhouse?

**Comment by lomik** [comment]
graphite-clickhouse from master has experimental implementation of tags autocomplete api http://graphite.readthedocs.io/en/latest/tags.html#auto-complete-support
This works in grafana 5

**Comment by Perlovka** [comment]
Thanks!
Though this is not documented, found it here:
https://github.com/grafana/grafana/pull/10139
