### ISSUE TITLE
Automate packages pushing for autobuilds and releases

### ISSUE THREAD

**Issue by Hipska** [lomik/graphite-clickhouse#164]
0.12.0 is the latest available.

**Comment by Felixoid** [comment]
It's in the closest plans to fix package uploading there.

**Comment by Felixoid** [comment]
The package is already available on packagecloud, you can check it out. The automated push will be implemented in #165

**Comment by Felixoid** [comment]
The autobuilds don't work yet

**Comment by Hipska** [comment]
It seems the new release isn't pushed to packagecloud yet..

**Comment by Hipska** [comment]
@msaf1980 It seems the new release isn't pushed to packagecloud yet..

**Comment by msaf1980** [comment]
@Hipska Done for graphite-clickhouse
