### ISSUE TITLE
Wrong glibc version in Debian Buster

### ISSUE THREAD

**Issue by lamaral** [lomik/graphite-clickhouse#170]
Hello guys,

After upgrading my graphite-clickhouse from 0.12 to 0.13 on my Buster machine, graphite-clickhouse couldn't start anymore, presenting an error:
```
/usr/bin/graphite-clickhouse: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/bin/graphite-clickhouse)
```

Buster runs 2.28, according to ldd:
```
$ ldd --version
ldd (Debian GLIBC 2.28-10) 2.28
```

I am using the packages from go-graphite in packagecloud.io.

Let me know if I can provide you with any extra info. 

Thanks,
Luiz

**Comment by Felixoid** [comment]
It's built statically now https://packagecloud.io/go-graphite/autobuilds/packages/debian/buster/graphite-clickhouse_0.13.0-18-g5fa89c9_amd64.deb
