### ISSUE TITLE
No data from default rollup policy

### ISSUE THREAD

**Issue by Perlovka** [lomik/graphite-clickhouse#20]
Hi,

We are using carbon-clickhouse as remote storage for prometheus, with tags (graphite + graphite_tagged tables). Data is sent every 15s.

graphite-clickhouse does not return data for series less than 1 hour ago with the following rollup config:

```
    <graphite_rollup>
        <pattern>
            <regexp>nginx_http_stats_requests</regexp>
            <function>sum</function>
            <retention>
                <age>3600</age>
                <precision>60</precision>
            </retention>
        </pattern>
        <default>
            <function>any</function>
            <retention>
                <age>0</age>
                <precision>15</precision>
            </retention>
        </default>
    </graphite_rollup>
```

grafana request to graphite-web:

```
aliasByTags(groupByTags(perSecond(seriesByTag('name=nginx_http_stats_requests_count', 'region=~${region:regex}', 'job=~$role', 'http_host=~$http_host','http_code=~$http_code')), 'sum', 'hostname','http_code'), 'hostname', 'http_code')
```

When requesting data for the last 3 hours, it returns as expected, graph is populated up to last minute.
When requesting last 30 minutes, all datapoints are null.

**Comment by lomik** [comment]
You should add retention with age=0 to nginx_http_stats_requests pattern section. 
Default section is used only for series not matched by any pattern. See https://clickhouse.yandex/docs/en/table_engines/graphitemergetree/ for details.

**Comment by Perlovka** [comment]
Oh, I thought that default is used for series not covered by any retention policy. Thanks!
