### ISSUE TITLE
Basic explanation

### ISSUE THREAD

**Issue by ipeacocks** [lomik/graphite-clickhouse#24]
Could you explain in a few words what does `graphite-clickhouse`? I am familiar with basic original Graphite stack:

* Carbon
* Whisper
* Graphite-web (api for Grafana and basic web panel).

Per my understanding in clickhouse case `graphite-clickhouse` needs to be located before `clickhouse` for providing the same metrics (as Whisper) for Graphite frontend (Graphite-web or carbonapi etc). Is it correct? Useful links are also appreciated.

**Comment by deniszh** [comment]
IMO you can find pretty good explanation in https://medium.com/avitotech/metrics-storage-how-we-migrated-from-graphite-whisper-to-graphite-clickhouse-a8299e5b057
