### ISSUE TITLE
Strange behavior for rolluped data

### ISSUE THREAD

**Issue by agend** [lomik/graphite-clickhouse#25]
Hi,
  I have set up following rollup:
```
<graphite_rollup>
       <default>
               <function>avg</function>
               <retention>
                       <age>0</age>
                       <precision>1</precision>
               </retention>
                <retention>
                       <age>86400</age>
                       <precision>60</precision>
               </retention>
               <retention>
                       <age>63072000</age>
                       <precision>86400</precision>
               </retention>
       </default>
</graphite_rollup>
```

And got expected results for first interval (30 min) but after got null values between actual values returned from graphite (see screenshot).
![rolluped data example](https://user-images.githubusercontent.com/2485016/46297517-8a938700-c5a5-11e8-80a4-5ee4a1e2ca88.png)
Am I misconfigured it?

**Comment by lomik** [comment]
Rollup rules for graphite-clickhouse and for clickhouse-server are equal?

**Comment by agend** [comment]
Yeap, I had different configs. Thank you.
