### ISSUE TITLE
date-tree-table-version gets broken in 0.7

### ISSUE THREAD

**Issue by ivanich** [lomik/graphite-clickhouse#26]
We use the following table for date-tree
graphite.date_metrics ( Path String,  Level UInt32,  Date Date ) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/graphite.date_metrics', '{replica}', Date, (Level, Path, Date), 8192) AS SELECT toUInt32(length(splitByChar('.', Path))) AS Level, Date, Path FROM graphite.data;

Starting from graphite-clickhouse-0.7 it tries to query with Deleted field even when date-tree-table-version is being set to 1.

**Comment by lomik** [comment]
fixed in master
