### ISSUE TITLE
Supported version of protocol

### ISSUE THREAD

**Issue by grzkv** [lomik/graphite-clickhouse#28]
Looks like the protocol in https://github.com/lomik/graphite-clickhouse/blob/master/carbonzipperpb/carbonzipper.proto is derived from v1 of [`go-graphite/protocol`](https://github.com/go-graphite/protocol).

How about supporting v2 or v3? Are there any fundamental limitations to this?

**Comment by lomik** [comment]
v1 and v2 protocols are equal (except of carbonserver specific methods). 
v3 supported only in latest versions of go-graphite/carbonapi. I use carbonapi-0.9.2 with some patches

**Comment by grzkv** [comment]
So, looks like we can use your lib if we support v2, right?

**Comment by lomik** [comment]
I don't understand. What "lib" you want to use?

**Comment by grzkv** [comment]
I mean, `graphite-clickhouse`. It's not a lib, sorry for misnaming it.

**Comment by Felixoid** [comment]
Since #85 the project supports pbv3, so it's solved
