### ISSUE TITLE
How to use tags right

### ISSUE THREAD

**Issue by MetikovVadim** [lomik/graphite-clickhouse#31]
Hello!
When i trying using tags i get : 
$ graphite-clickhouse -tags
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7b9ad2]

goroutine 1 [running]:
github.com/lomik/graphite-clickhouse/tagger.(*Set).Merge(0x0, 0x0, 0x1104955)
	/root/go/src/github.com/lomik/graphite-clickhouse/_vendor/src/github.com/lomik/graphite-clickhouse/tagger/set.go:53 +0x22
github.com/lomik/graphite-clickhouse/tagger.Make(0xc420210000, 0x8, 0x1)
	/root/go/src/github.com/lomik/graphite-clickhouse/_vendor/src/github.com/lomik/graphite-clickhouse/tagger/tagger.go:225 +0xd23
main.main()
	/root/go/src/github.com/lomik/graphite-clickhouse/_vendor/src/github.com/lomik/graphite-clickhouse/graphite-clickhouse.go:149 +0x3b5

**Comment by lomik** [comment]
`graphite-clickhouse -tags` is command for my own alternative tagging system. I doubt that you are interested in it. Most likely you are looking for how to use standard tags, which are described here https://graphite.readthedocs.io/en/latest/tags.html

See how the `graphite_tagged` table is created and used in this repository https://github.com/lomik/graphite-clickhouse-tldr

**Comment by blind-oracle** [comment]
@lomik Can you explain in short what's the advantage of the reversed series/points? And why it's used in the default docket image.

**Comment by lomik** [comment]
@blind-oracle 

Reverse table works extremely faster for queries like this "telegraf.*.cpu.cpu-total.usage_user" (postfix without wildcards).

In tables with default path metrics "telegraf.host1.cpu.cpu-total.usage_user" and "telegraf.host2.cpu.cpu-total.usage_user"  are located far apart (in separate data blocks). In reverse tables this metrics go in a row.  This minimizes the number of checked data blocks and index searches.

Reverse tables work slower only on queries like 'telegraf.host1.cpu.cpu-total.*'.  But such requests are unusual in most installations

**Comment by blind-oracle** [comment]
@lomik 

Yep, I thought so, but wondered if there are any other reasons. Thanks!
It seems that we can store both forward and reverse metrics using *carbon-clickhouse*, but use only one type for *graphite-clickhouse*. Aren't there any plans to combine them and query different tables based on wildcard format?

The only way I see it now is to have a separate "graphite-clickhouse -> carbon-zipper -> carbon-api -> grafana source" chains for different graphs.

**Comment by lomik** [comment]
>  Aren't there any plans to combine them and query different tables based on wildcard format? 

You can do this with this config
```
[[data-table]]
table = "graphite_reverse"
target-match-all = ".*[.][a-zA-Z0-9_-]+$"
reverse = true

[[data-table]]
table = "graphite"
reverse = false
```

**Comment by ralphM78** [comment]
Hello,

[[data-table]]
table = "graphite_reverse"
target-match-all = ".*[.][a-zA-Z0-9_-]+$"
reverse = true

works perfectly . But how I can address reverse series ? I have tried

[[data-table]]
table = "graphite_seriesreverse"
target-match-all = ".*[.][a-zA-Z0-9_-]+$"
reverse = true

but this doesn't work.

**Comment by lomik** [comment]
@ralphM78 series reverse table can be used only for all queries. 
```
[clickhouse]
date-tree-table = "graphite_seriesreverse"
date-tree-table-version = 2
```

**Comment by ralphM78** [comment]
date-tree-table-version = 3
make it work. Thanks a lot.

**Comment by lomik** [comment]
@ralphM78 really 3, I wrote incorrectly above.
