### ISSUE TITLE
missing values for 1s precision under stress test

### ISSUE THREAD

**Issue by aksakalli** [lomik/graphite-clickhouse#33]
I am running graphite-clickhouse with [the recommended docker-compose](https://github.com/lomik/graphite-clickhouse-tldr) and I am conducting a stress test with [a command line tool](https://github.com/feangulo/graphite-stresser).

I publish metrics every second from metrics like `STRESS.host.ip-0.com.graphite.stresser.a.count`, I changed the `rollup.xml` to test its performance such like:

```
<yandex>
    <graphite_rollup>
        <pattern>
            <regexp>^STRESS\.</regexp>
            <function>avg</function>
            <retention>
                <age>0</age>
                <precision>1</precision>
            </retention>
            <retention>
                <age>120</age>
                <precision>5</precision>
            </retention>
            <retention>
                <age>600</age>
                <precision>60</precision>
            </retention>
        </pattern>
        <default>
            <function>avg</function>
            <retention>
                <age>0</age>
                <precision>60</precision>
            </retention>
            <retention>
                <age>2592000</age>
                <precision>3600</precision>
            </retention>
        </default>
    </graphite_rollup>
</yandex>
```
(I tried with `avg` function as well but the problem persisted.)

It is returning inconsistent, gapped points:

```
watch -n 1 "curl 'localhost:8080/render/?target=STRESS.host.ip-0.com.graphite.stresser.a.count&format=csv&from=-30s'"
```

![Peek 2019-04-03 15-56](https://user-images.githubusercontent.com/1939193/55484637-28394300-5629-11e9-88c0-e1d23033648e.gif)

```
watch -n 1 "curl 'localhost:8080/render/?target=STRESS.host.ip-0.com.graphite.stresser.a.count&format=csv&from=-150s&to=-120'"
```
![Peek 2019-04-03 16-01](https://user-images.githubusercontent.com/1939193/55484987-cc22ee80-5629-11e9-83a1-f6b550113ea7.gif)

**Comment by blind-oracle** [comment]
What about the database? Have you checked that the data is there actually?

**Comment by Felixoid** [comment]
It looks to me like an issue mentioned in https://github.com/ClickHouse/ClickHouse/issues/5582 and https://github.com/ClickHouse/ClickHouse/issues/5726

**Comment by Felixoid** [comment]
Hey @aksakalli,  
As ClickHouse/ClickHouse#5582 is closed now, I'd like to reproduce your issue. How may I do it? How do you run the stresser?

**Comment by Felixoid** [comment]
@aksakalli, should I close the issue?
