### ISSUE TITLE
How to configure logging

### ISSUE THREAD

**Issue by matthew-hollick** [lomik/graphite-clickhouse#34]
Hi,
we use graphite-clickhouse and carbon-clickhouse in production and are very happy with the performance improvements over our previous graphite stack.
the query logging is too much for us but we would like to keep the access logging.
So, ideally we would like to log query at warn and everything else at info.
We have unsuccessfully tried this configuration but feel that we are misunderstanding how this should work:

```
[[logging]]
logger = "query"
file = "/var/log/graphite-clickhouse/graphite-clickhouse.log"
level = "warn"
encoding = "mixed"
encoding-time = "iso8601"
encoding-duration = "seconds"

[[logging]]
logger = ""
file = "/var/log/graphite-clickhouse/graphite-clickhouse.log"
level = "info"
encoding = "mixed"
encoding-time = "iso8601"
encoding-duration = "seconds"
```
we reversed the ordering and tried playing around with it in general but the result is the same - when we set any logger to be warn we get no logs, we dont see many warnings or errors so I guess we may not have been patient enough for them but I would have expected to see many access log lines.

Cheers!

- the friendly telemetry team at UK HMRC (tax people.)

**Comment by lomik** [comment]
Hi,

I checked your configuration and it works. In /var/log/graphite-clickhouse/graphite-clickhouse.log I see many access logs and nothing else

**Comment by matthew-hollick** [comment]
Thank you kindly for testing this.

yes.... trying it again it works perfectly as expected.

No idea how we got this so wrong.

Sorry for wasting your time.

Matthew.
