### ISSUE TITLE
Tag table usage

### ISSUE THREAD

**Issue by bzed** [lomik/graphite-clickhouse#5]
Please document the usage of the 'tag' table and config files.

**Comment by lomik** [comment]
Basic information about tags usage located here https://github.com/lomik/graphite-clickhouse/wiki/TagsRU . Now in Russian. I will try to translate it in the near future.

Short manual:
1. Create table and enable it in config: `tag-table = "graphite_tag"`
2. Create files with rules: `/etc/graphite-clickhouse/tag.d/*.conf`
3. Run `graphite-clickhouse -tags` for fill table graphite_tag (put it into crontab)
4. Check `_tag` directory in graphite web ui

**Comment by volfco** [comment]
Echoing the request for more documentation on tags. I'm having issues getting tags to work at this end and I would like to make sure everything is correct before I open more issues.

**Comment by bzed** [comment]
@volfco you might want to look into the new graphite tag system. #18 has a short description with links.
