### ISSUE TITLE
"deleted" for index tables

### ISSUE THREAD

**Issue by bzed** [lomik/graphite-clickhouse#50]
Hi,

the old graphite_tree table had a "deleted" row to mark Paths as deleted - which was very helpful in those cases where badly named series appeared for whatever reason.
Is there a way to make this work with the index table?

Thanks,
Bernd

**Comment by lomik** [comment]
"Deleted" hack is not required with modern versions of clickhouse. Use "ALTER TABLE graphite_tree DELETE WHERE expr" 
https://clickhouse.yandex/docs/en/query_language/alter/#alter-mutations

**Comment by bzed** [comment]
Nice, I've missed that change somehow, too much going on in the clickhouse world. thanks for the pointer!
