### ISSUE TITLE
aliasByTags not working correctly

### ISSUE THREAD

**Issue by Hipska** [lomik/graphite-clickhouse#66]
Hi, it seems that this backend does not support tag queries very well when there is also some computation.

The following query displays the series as `perSecond(interface_in_octets` and `perSecond(interface_out_octets`:
```graphite
aliasByTags(perSecond(seriesByTag('hostname=$host', 'ifName=~${interface:regex}', 'name=~interface_(in|out)_octets')), 'name')
```
While the following query works correct (but does not show correct data):
```graphite
aliasByTags(seriesByTag('hostname=$host', 'ifName=~${interface:regex}', 'name=~interface_(in|out)_octets'), 'name')
```

**Comment by Civil** [comment]
As far as I understand, graphite-clickhouse do not support any functions. I assume you are talking about carbonapi and this issue: https://github.com/go-graphite/carbonapi/issues/390

**Comment by Hipska** [comment]
Yes, I wrongly assumed the problem was here and not on `carbonapi`. My bad.

**Comment by Hipska** [comment]
Hi @Civil, could you have a look at go-graphite/carbonapi#422?
