### ISSUE TITLE
404 when returning empty metric set

### ISSUE THREAD

**Issue by matthew-hollick** [lomik/graphite-clickhouse#74]
Hi,
I trust you and your loved ones are well and safe.

I'm probably misunderstanding things here so your patience is appreciated.

It appears that when an empty data set is returned it is done so with a http 404 status.
I'm honestly not sure if this is intentional but the behaviour appears to trigger the retry functionality in carbonapi, it could be that it should not...

So my question is, should graphite-clickhouse return a 404 when correctly returning an empty data set?

 Thanks.

**Comment by lomik** [comment]
Hi,

Code 404 was added in this PR: https://github.com/lomik/graphite-clickhouse/pull/39

**Comment by matthew-hollick** [comment]
thanks for the speedy reply.
I'm going to chat to the carbonapi project then, I'm pretty convinced that an empty data set should not trigger a retry event as it is a valid response.
