### ISSUE TITLE
bufio.Scanner

### ISSUE THREAD

**Issue by ralphM78** [lomik/graphite-clickhouse#87]
Hi,

as I mentioned in https://github.com/lomik/graphite-clickhouse/issues/67#issuecomment-675288394 would it be possible to make bufio.Scanner a config option and print out a clear log message if the size is too small ? I have increased the size again to look backwards more than 75 days. 
@ihard where have you seen this error message ? I haven't seen it. Have to find out the hard way.
No idea what the right fixed size could be. Maybe someone would like to look backwards some years.
So make it a config option would be nice if it's possible. I'm really not a developer so I can't do it by myself
.
Ralph

**Comment by Felixoid** [comment]
Hey @ralphM78, could you, please, try the #93? BTW, to get rid of the issue with 100% sure you should enable `internal-aggregation`, see #88

**Comment by ralphM78** [comment]
Hi,

I have tried it and it looks good so far. Now I will have a look at internal-aggregation.
Thanks to you

**Comment by Felixoid** [comment]
I assume it's done with #93
