### ISSUE TITLE
rollup-conf and reverse Path

### ISSUE THREAD

**Issue by alexandv** [lomik/graphite-clickhouse#89]
Hello,

I'm using the reversed Path for the data table. It works well however the rollup conf in graphite-clickhouse does not seem to work with regexps on the reversed Path. So I have to maintain 2 rollup.xml files: 1 for graphite-clickhouse that applies to the non-reversed Path and another for clickhouse that works on the reversed Path. For example:
For graphite-clickhouse:
```
        <pattern>
                <regexp>^carbon\.</regexp>
                <function>avg</function>
                <retention>
                        <age>0</age>
                        <precision>60</precision>
                </retention>
                <retention>
                        <age>1296000</age>
                        <precision>600</precision>
                </retention>
        </pattern>
```

And for CH:
```
        <pattern>
                <regexp>\.carbon$</regexp>
                <function>avg</function>
                <retention>
                        <age>0</age>
                        <precision>60</precision>
                </retention>
                <retention>
                        <age>1296000</age>
                        <precision>600</precision>
                </retention>
        </pattern>
```

Would it be possible to use the same logic in graphite-clickhouse as in CH?

**Comment by Felixoid** [comment]
Unfortunately, when you use tables with reversed points, you have to make the mirrored ClickHouse retention config manually. Since there are regexps, I can't see how it would be automated
