### ISSUE TITLE
Release 0.12.0 with internal-aggregation ?

### ISSUE THREAD

**Issue by deniszh** [lomik/graphite-clickhouse#95]
Hi @Felixoid @lomik ,

Maybe it's time for next release, with `internal-aggregation` merged?

**Comment by Farfaday** [comment]
also relates to #78

**Comment by deniszh** [comment]
@Felixoid : great, thanks!
Could you please upload new release to https://hub.docker.com/r/lomik/graphite-clickhouse/tags too?

**Comment by Felixoid** [comment]
Sorry, I don't have rights there. It makes sense to add auto-builds there, though
