### ISSUE TITLE
Add versions compatibility to README.md

### ISSUE THREAD

**Issue by Felixoid** [lomik/graphite-clickhouse#98]
After the new release, the incompatibilities with carbonapi older than 0.14 were found.

The https://github.com/lomik/graphite-clickhouse#compatibility should be updated. I'm waiting for an answer from Denis Zhdanov if graphite-web works fine here

**Comment by deniszh** [comment]
I made a quick test using my QA clusters and also https://github.com/deniszh/graphite-clickhouse-cluster-tldr - looks like it's still working, at least with latest graphite-web (1.1.7)

**Comment by Felixoid** [comment]
Done in 927334d6e790061057955a2600981989488da4b1
